### PR TITLE
make Point field nullable

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@nathanbegbie you won't believe!! I managed to get it to work!!
I installed GDAL from [here](http://www.kyngchaos.com/software:frameworks) and 

After installing, I ran into this issue
```
OSError: dlopen(/usr/local/lib/libgdal.dylib, 6): Library not loaded: /usr/local/opt/giflib/lib/libgif.7.dylib
  Referenced from: /usr/local/lib/libgdal.dylib
  Reason: image not found
```

and fixed it by linking the new version I installed from the package
```
$ rm /usr/local/lib/libgdal.dylib
$ ln -s /Library/Frameworks/GDAL.framework/Versions/1.11/unix/lib/libgdal.dylib /usr/local/lib/
```

then ran into `libxml2` issue, turns out it was just not linked
```
$ brew install libxml2 --with-xml-config
Warning: libxml2-2.9.4_2 already installed, it's just not linked.
```
```
brew link --force libxml2
```

and tada!! :tada:

screen shot 2017-04-17 at 3 20 19 pm

**Comment by miltontony** [comment]
Celebrated too early 😭 
Eventually got it to work by uninstalling everything (postgres, postgis, gdal) and using pre-compiled versions. The brew version of `postgres/gis/gdal` feels broken.
http://www.kyngchaos.com/software/frameworks 
and 
http://www.kyngchaos.com/software/postgres

Worked like a charm!

**Comment by miltontony** [comment]
@nathanbegbie ready for review

**Comment by nathanbegbie** [comment]
@miltontony SRID is a setting for the type of projection that you want to use: so for e.g. if you want to consider the distance between 2 points on the globe, it can either be straight or curved. More info: https://docs.djangoproject.com/en/1.11/ref/contrib/gis/model-api/#srid

**Comment by nathanbegbie** [comment]
:+1: 🍰

**Pull request merged**
